### ISSUE TITLE
Remove advertising from docs

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest-docs#103]
There's an ad in the TOC

**Comment by willscripted** [comment]
Is this project hosted on rtfd? If so, it looks like there is an [opt-out](https://docs.readthedocs.io/en/latest/ethical-advertising.html#opting-out) option in the admin dashboard.

**Comment by steve-chavez** [comment]
readthedocs have been serving us well and the ad is not that invasive.

Witnessing myself how hard is to get funding for an oss project I think we should support them in any we can.
