### ISSUE TITLE
add example of how to configure postgrest when using pm2

### ISSUE THREAD

**Issue by barbalex** [PostgREST/postgrest-docs#105]
[The configuration docs](https://postgrest.com/en/v4.3/install.html#configuration) show how to get postgrest running:

    postgrest /path/to/postgrest.conf

Should that not be `./postgrest /path/to/postgrest.conf`? It is a binary, not an npm script

Doing this in dev mode is easy:

    ./postgrest postgrest.conf

I am probably just a very bad noob but it cost me hours to find out that the correct way to pass the configuration file in production, i.e. when using pm2 for this is:

    pm2 start ./postgrest -- postgrest.conf

Would you be open for a pull request adding this example to [the configuration docs](https://postgrest.com/en/v4.3/install.html#configuration)?

**Comment by begriffs** [comment]
Sorry that the syntax in the example made you lose a bunch of time. Yeah please send a pull request to the docs to clarify.
