### ISSUE TITLE
Document how to do schema reloading on windows

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest-docs#114]
Windows doesn't have a SIGHUP signal, and that's currently how you tell PostgREST to reload the schema. In the future when hasql supports LISTEN/NOTIFY we can listen for a db notification to trigger this. Until then @gcloeval contributed a batchfile to do it:

```batch
REM to run pass postgrest.exe CONFIG_FILE_NAME, ex: c:\workspace>restartpgrest.bat postgrest.exe pgrest.config
@if %1.==. (goto error) ELSE (goto restart)

:restart
@taskkill /f /im %1 >nul
@timeout /t 3 /nobreak >nul
@echo now starting %1
%1 %2
@echo restart complete
@goto exit

:error
@echo Please specify a program...
@goto exit

:exit
```

Add this to the docs about schema reloading.

**Comment by laurenceisla** [comment]
@steve-chavez I think this was solved in https://github.com/PostgREST/postgrest-docs/pull/408#discussion_r676029939?

**Comment by steve-chavez** [comment]
True. Closing.
