### ISSUE TITLE
IS Not Support PostGIS Function?

### ISSUE THREAD

**Issue by haopingpang** [PostgREST/postgrest-docs#143]
I test  PostgREST with PostGIS Function ,But Message Prompts function  does not exist. eg: st_geomfromtext(text),st_AsGeoJson( )

**Comment by steve-chavez** [comment]
Provide your PostgreSQL and PostgREST versions, also a minimal SQL definition plus how you make the request to PostgREST and the response body, so I can reproduce your issue.

I've tested a view that has `st_asgeojson` on the latest version and it's working fine for me.

**Comment by steve-chavez** [comment]
Probably it's a `search_path` issue, try appending `public`(the schema where you created PostGIS) to the functions(like `public.st_asgeojson`) in your view definition.

**Comment by haopingpang** [comment]
I have tested as steve-chavez's suggestion, steve-chavez  is right Thanks for  steve-chavez's suggestion @steve-chavez
