### ISSUE TITLE
how to use db-schema?

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest-docs#160]
I am running `docker run --rm --net=host -p 3000:3000  -e DB_SCHEMA=test  -e PGRST_DB_URI="postgres://postgres:etc@localhost:5432/etcdb"   -e PGRST_DB_ANON_ROLE="postgres"   postgrest/postgrest  &` 

And to test I also used at SQL a public  `create table t `, but all other data is at SQL's `CREATE schema test`. Eg. there was `create table test.t`... So, `http://localhost:3000/t` is fine (!),  BUT:

`http://localhost:3000/test.t` is an error, *"relation "public.test.t" does not exist"*.

so, how to use DB_SCHEMA env, or how to say that I need a SQL-schema name that is not `public`?

**Comment by steve-chavez** [comment]
The env var is `PGRST_DB_SCHEMA`, here is a list of the env vars for the docker image https://github.com/PostgREST/postgrest/blob/master/docker/Dockerfile#L27-L39.

**Comment by ppKrauss** [comment]
Hi, perfect, the PGRST_DB_SCHEMA variable is working fine. 

Well, the [GUIDE](https://postgrest.org) is **very confuse** about the use of the term "schema". In particular, if DB_SCHEMA (the "database schema" so "SQL database" so in the sense of SQL's  SCHEMA)  is not SQL-SCHEMA, I have no ideia why we set it with any value.

-----

Another problem: how to use 2 instances of PostgREST? Can I run docker with different ports to use different parameters (eg. changing PGRST_DB_SCHEMA or PGRST_DB_URI)? I try it but perhas I do something wrong.

**Comment by ppKrauss** [comment]
Hi @steve-chavez, thanks, PGRST_DB_SCHEMA is working fine (!).

The term "schema" is confuse, the suggestion is to change documentation, can I edit there?

------

Now I have two new problmes:

1. How to build mulple instances (varing the parameter   PGRST_DB_SCHEMA) of PostgREST with `docker run` 

2. How to use RPC, I using copy/paste [function of the documentation](https://postgrest.org/en/v5.0/api.html#stored-procedures), but impossible to call it by GET as you the documensay. I use http&#47;/:localhost:3000/rpc/add_them?a=1&b=2  but it is an ERROR , "function test.add_them() does not exist".

The  root also shows correct function definition, 
```json
{
"/rpc/add_them":{
  "post":{
     "tags":["(rpc) add_them"],
     "produces":["application/json","application/vnd.pgrst.object+json"],
     "parameters":[{
          "required":true,"schema":{"required":["a","b"],
          "type":"object",
          "properties":{"a":{"format":"integer","type":"integer"},"b":{"format":"integer","type":"integer"}}},
          "in":"body","name":"args"
        },{"$ref":"#/parameters/preferParams"}],"responses":{"200":{"description":"OK"}
   }}}
}

**Comment by ppKrauss** [comment]
Thanks @steve-chavez, 1 and 2 are solutions and are working fine with my server (!). 

We can close this issue.
