### ISSUE TITLE
How to document overloaded RPC functions

### ISSUE THREAD

**Issue by mdr1384** [PostgREST/postgrest-docs#163]
Would it be possible to support OpenAPI documentation on overloaded RPC functions?
For example our API has 3 versions of the `login` RPC call which returns an authorization token:

- `login(session_id TEXT)`
- `login(username TEXT, password TEXT)`
- `login(sip_registration TEXT, sip_auth_password TEXT, pin TEXT)`

The current OpenAPI output only shows the 3-argument version.   Also, do you have any recommendations about how to document function arguments as you cannot `COMMENT ON...` them.  Putting the argument documentation in the function comment seems a bit of a cop-out.

**Comment by steve-chavez** [comment]
You can use multi-line comments for specifying arguments, for example:
```sql
create or replace function test.overloaded(a int, b int) returns int as $$
  select a + b
$$ language sql;

comment on FUNCTION test.overloaded(a int, b int) IS $$
Returns the sum of two values

a: first int value to be summed
b: second int value to be summed
$$;
```
You can also have a different comment on each overloaded function. I think these capabilities pg offers us are good enough for documenting functions.

About the OpenAPI output, let's continue that discussion in https://github.com/PostgREST/postgrest/issues/1154.
