### ISSUE TITLE
No clues in the docs about RPC with anonymous parameter or function overload-bug

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest-docs#164]
The example 

```sql
CREATE FUNCTION add_them(a integer, b integer) RETURNS integer AS $$
 SELECT $1 + $2;
$$ LANGUAGE SQL IMMUTABLE STRICT;
```

is good but not sufficient to understand another typical uses, like the simplest parametrized one, 

```sql
CREATE FUNCTION hello(text) RETURNS text AS $$
 SELECT 'Hello ' || $1 || '!';
$$ LANGUAGE SQL IMMUTABLE STRICT;
```
so, **how to call it?**, there are no answer or evident comment about. 

... And about overloading resolution?  A second function

```sql
CREATE FUNCTION hello(p1 int) RETURNS text AS $$
 SELECT 'Hello ' || $1 || '!';
$$ LANGUAGE SQL IMMUTABLE STRICT;
```
will replace the first, so `http://localhost:3000/rpc/hello?p1=123` now returns "Hello (int) 123!", but  `http://localhost:3000/rpc/hello?p1=XX123`  will produce an error, not the original (overload) function result.

-----

PS: as an enhancement suggestion, ideal is to use anonymous parameters as positonal parts, eg. `http://localhost:3000/rpc/hello/world`

**Comment by steve-chavez** [comment]
This is mentioned in the docs on [stored procedures](https://postgrest.org/en/v5.0/api.html#stored-procedures): **Procedures must be used with named arguments**.

I think what's confusing about this is that the `add_them` example names the arguments but then it goes right ahead and uses [positional parameters](https://www.postgresql.org/docs/10/static/sql-expressions.html#SQL-EXPRESSIONS-PARAMETERS-POSITIONAL), it should be like this:
```sql
CREATE FUNCTION add_them(a integer, b integer) RETURNS integer AS $$
 SELECT a + b;
$$ LANGUAGE SQL IMMUTABLE STRICT;
```
I think it'd be better to clarify the docs than to support positional notation on the functions, named arguments keep the URL consistent(no nested routes) and don't contribute to ambiguity(relying on the position of the args seems error prone for API consumers).

**Comment by ppKrauss** [comment]
> This is mentioned in the docs on stored procedures: Procedures must be used with named arguments.

Hum, ok, so the PostgREST magic is not for *any* function, only named. Well, will be good bold and red letters at docs.

Need also bold and red letters to say "DANGER: not overload functions", 
```sql
CREATE FUNCTION add_them(a text, b text) RETURNS integer AS $$
 SELECT a || b;
$$ LANGUAGE SQL IMMUTABLE STRICT;
```
The PostgREST behaviour is not predicable about `add_them(a text, b text)` + `add_them(a integer, b integer)`.
 
------

... My other comments are not about the bug or documentation, is only a **suggestion**, because in REST tradiction of endpoints in the form `http://etc/{p1}/{p2}`  are positional, so **will be natural** in a REST-oriented tool/support to be also positional. Will be natural to use  `http://localhost:3000/rpc/add_them/123/456` (optional for named and perfect for non-named).

**Comment by steve-chavez** [comment]
We could add emphasis to the named arguments part, I agree. 

Your overloaded function example is a more of a theoretical one, real use cases will likely have differently named arguments(and varying number) for different types, like this example presented in #163:

- `login(session_id TEXT)`
- `login(username TEXT, password TEXT)`
- `login(sip_registration TEXT, sip_auth_password TEXT, pin TEXT)`
