### ISSUE TITLE
Using '&' and '=' in a query 

### ISSUE THREAD

**Issue by txjoe** [PostgREST/postgrest-docs#174]
A crawler I wrote stores some urls in a Postgres db using an postgrest api

This was one of the urls 
http://website.com/viewtopic.php?f=16&p=44

Later when I tried to query the db using the api to check if the url was in the db, the response had this

"details":"unexpected "4" expecting "not" or operator (eq, gt, ...)","message":""failed to parse filter (44)" (line 1, column 1)"

Is there a way to store the urls in a way that the '&'s and '='s in a string I'm trying to search don't affect the query?

PS : this is the function which was used for querying the db

```
def check_if_discussion_has_been_scraped(url):
    global jwt_token
    headers = {
        'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + jwt_token,
    }
    query = 'http://localhost:3000/fsdiscussions?url=eq.%s'%url
    r = requests.get(query, headers=headers)
    if r.status_code not 200:
        logger.error('Failed to query db |'+str(r.status_code)+' | '+r.text+' | '+r.reason)
        exit(1)
    if r.text == '[]':
        return False
    else:
        return True
```

**Comment by steve-chavez** [comment]
You'll need to urlencode the url, that way `&` is converted to `%26` which doesn't break the query param.

You could do that in your python code or pg(some options [here](https://stackoverflow.com/questions/10318014/javascript-encodeuri-like-function-in-postgresql), also check this [extension](https://github.com/petere/pguri)).

**Comment by txjoe** [comment]
Thanks @steve-chavez , that worked
