### ISSUE TITLE
postgrest.conf in docker

### ISSUE THREAD

**Issue by ASVBPREAUBV** [PostgREST/postgrest-docs#176]
i could not find a way to load a postgrest.conf in the official docker container.
Since the Dockerfile on [the official docker Container](https://hub.docker.com/r/postgrest/postgrest/) is not visible i would need a way to do that.

**Comment by steve-chavez** [comment]
Here's the [Dockerfile](https://github.com/PostgREST/postgrest/blob/master/docker/Dockerfile), I'll see if I can include this in the description of the official docker image.

Also all the config settings are passed as env vars in the docker container(prefixed with PGRST, as in the example [here](https://postgrest.org/en/stable/install.html#containerized-postgrest-with-native-postgresql)) so is not really necessary to manipulate the internal postgrest.conf.

**Comment by ASVBPREAUBV** [comment]
thanks for the fast help
