### ISSUE TITLE
Help with RLS

### ISSUE THREAD

**Issue by pixie79** [PostgREST/postgrest-docs#194]
Hi,

I am struggling with RLS, I know i can set a policy ok that checks the JWT email claim however, I can not use the email as the postgres role. The limit on the PG_users is too short for many of our email addresses. So instead i have a staff table that maps email to staffid (uuid). This uuid i can then create as a role with inheritance correctly in the PG_roles table.

Here is where i am stuck, our JWT has no way of knowing what the staffid is it only knows about email. So Postgrest needs to user the email, but some how i need the RLS policy to map email to staffid(role).

Any ideas or simple examples available?

Thanks

Mark

**Comment by ruslantalpa** [comment]
Not strictly the answe to your question but i think you are heading in the wrong direction

You dont need to have a database user fore every application user.

Start by looking at these links (in this order)
https://medium.freecodecamp.org/stop-calling-postgrest-magic-8f3e1d5e5dd1
https://blog.2ndquadrant.com/application-users-vs-row-level-security/
https://github.com/subzerocloud/postgrest-starter-kit/blob/master/db/src/authorization/privileges.sql

**Comment by pixie79** [comment]
Hi @ruslantalpa 

Thanks for that, I figured i was over complicating it mostly be trying to keep it easy.

So I think you are saying the following, the DB only requires 4 actual users
* postgres (admin)
* authentication (login user, no other access than to change role)
* anon ( the unauthenticated user role)
* system ( one or more JWT claim role for services calling the API)

Grants to the DB are then given as appropriate to the system and anon users. However on tables that need RLS, then a policy should be applied. eg, if the table includes a column for email then we can use the jwt email claim to match against. So far so good and this meets 90% of my needs.

However I have a few tables where instead of user I would like to have a col that might contain a list of teams who can access the record. Each staff member is a member of one or more teams and the mapping is held in the teams table. So i guess what i really need to know then is how do i write a policy that allows me to check if the jwt.claim.email is a member of the team for the current row ?

**Comment by ruslantalpa** [comment]
Yes, that is what i am saying.
You (usually) use database roles to represent “user groups/types” like admin/employee/customer then with rls you filter based on a specific user

As to the last part, see if this example helps you
https://gist.github.com/ruslantalpa/fea3e6a8b275633d1cab2cf45a4110fd

Specifically the knight_tool_access_policy

Note that it’s possible you will need to take the subselect part in that rls and place it in a “security definer” function (long explanation why and i’m on a phone)

**Comment by ruslantalpa** [comment]
Some context. That schema is modeling this “problem”

Suppose there are three types of obects in a database, gold, weapons and tools; three types of user, kings, knights and serfs. Kings are have access to all the gold, weapons and tools as long as they fall within their kingdom. Each knight is scoped to a kingdom, and can view their weapons and the tools belonging to any of their serfs. Serfs can only view their own tools.

**Comment by steve-chavez** [comment]
Will be addressed on #81.
