### ISSUE TITLE
Return Id of new posted object

### ISSUE THREAD

**Issue by HorunS** [PostgREST/postgrest-docs#210]
Hello guys!
Thank you for such great project.
But I stuck on one thing: I want to post object and I want to have id in response(because id is auto incremented). I found one way - creating of stored procedures. But is not good, because I will need to create that procedures for all tables.
How can I resolve my issue(getting posted object id on callback from posting process)?
Thanks!

**Comment by steve-chavez** [comment]
@HorunS Use the `Prefer: return=representation` header.

This is mentioned in http://postgrest.org/en/v5.2/api.html#insertions-updates.

**Comment by HorunS** [comment]
Great!! Thank you!!
