### ISSUE TITLE
Update schema reloading section

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#243]
Right now it only mentions it's needed for resource embedding. But now it's needed for other things.

See https://github.com/PostgREST/postgrest/issues/1376.

**Comment by steve-chavez** [comment]
Also add how to send docker a SIGUSR1

**Comment by pauldzy** [comment]
Oh and just as a note, the existing example for pg_listen on the 5.2 docs no longer works

`pg_listen <db-uri> ddl_command_end "killall -SIGUSR1 postgrest"`

should be changed to 

`pg_listen <db-uri> ddl_command_end /usr/bin/killall -SIGUSR1 postgrest`

I think PATH support went away around pg_listen commit #6 and I did not notice until this week.
