### ISSUE TITLE
Add multiple tables to the query/Nested resource embedding

### ISSUE THREAD

**Issue by maitrepylos** [PostgREST/postgrest-docs#275]
In the Resource Embedding section, it is not necessary to explain how to join more than two tables.
An example is proposed by @steve_chavez, is it possible to add it in the doc?

ex =  Films->Roles->Actors

`GET /films?select=*,roles(*,actors(*))&limit=10`

**Comment by steve-chavez** [comment]
@maitrepylos Sure! That example will be a good one to add.

**Comment by steve-chavez** [comment]
@maitrepylos Sure! That example would be a good one to add.
