### ISSUE TITLE
Uncertainty about section on function privileges

### ISSUE THREAD

**Issue by H20-17** [PostgREST/postgrest-docs#297]
I am newish to postgresql, so if I'm wrong I'm wrong and I apologise in advance. It says at https://postgrest.org/en/v6.0/api.html#stored-procedures

> Unlike tables/views, functions privileges work as a blacklist, so they’re executable for all the roles by default. You can workaround this by revoking the PUBLIC privileges of the function and then granting privileges to specific roles:

Specifically can you point me to somewhere online that demonstrates function privileges working as a blacklist. That would imply that you could do something like

```
REVOKE EXECUTE ON FUNCTION f(int8, text) FROM banned_user;
```
I didn't think it would work because if banned_user wasn't granted any rights in the first place, the revocation will have no effect behind the scenes. The banned user will still inherit EXECUTE on the function from PUBLIC just as before. I tested this, and unless my testing was wrong things worked the way I thought they would. I think that all privileges in postgresql are of the whitelist variety.

**Comment by H20-17** [comment]
Note that this may just be a terminological nitpick. In that case I just want the language revised.

**Comment by H20-17** [comment]
I would prefer that it said something like

> By default, the PUBLIC role is granted the EXECUTE privilege to every newly created function and by implication, all of the other roles will inherit this privilege. If, for some particular function, you want to restrict this function's use to specific roles, you must revoke the function's EXECUTE privilege from PUBLIC. Thereafter the function will only be usable by users who have specifically been granted the function's EXECUTE privilege.

**Comment by steve-chavez** [comment]
@H20-17 You're absolutely right about functions privileges not working as a blacklist. That was a bad analogy. The wording with PUBLIC you propose is much better.

If you'd like you could a PR with the change and I'll merge it.

**Comment by H20-17** [comment]
@steve-chavez I am happy to make a PR but what I wrote still wouldn't be fully sufficient because it's ot the literal truth. I think the following note or footnote also has to be included somewhere

> Although it was stated that the functions typically start off with EXECUTE privilege granted to PUBLIC, that's the effective truth but not the literal truth. In reality a function will start off with no privileges given to any role at all, and in that case the system behaves _as though_ PUBLIC was given the EXECUTE privilege. Therefore if you see a blank “Access privileges” field in the output of _\df++_, this implies that PUBLIC effectively has the function's EXECUTE privilege (even though it was never really granted). Thereafter, subsequent to any successful GRANT or REVOKE operation performed on the function, Postgresql will employ its conventional privilege system. Notably the presence of _=X/grantor_ indicates that PUBLIC has the EXECUTE privilege and, conversely, the absence of _=X/grantor_ will imply that PUBLIC does not have the EXECUTE privilege.

Those are just personal obvervations from my own experiments. I haven't read about it anyhwhere. I don't know if my description is perfect down to the last detail. I would like to know what you think about this before proceeding with a PR.

**Comment by H20-17** [comment]
@steve-chavez should the footnote be something simpler? Ideally I could just provide a link but I dont know where to find an online description other than my own.

**Comment by steve-chavez** [comment]
@H20-17 I also can't find a link for this on the pg documentation. Your description is more precise(so PUBLIC means not restricted by role, not that all ROLES have the privilege, right?), but perhaps a bit too low level for the docs.

I'm thinking we should overhaul the [Function privileges](http://postgrest.org/en/v6.0/api.html#function-privileges) section.

For an API, most users would prefer to be granular about function permissions so maybe we could start the section by recommending the users to run:

```sql
-- note the IN SCHEMA part
ALTER DEFAULT PRIVILEGES IN SCHEMA api REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
```
Wording here could be "by default postgres functions execution is not restricted by role, this snippet makes the following GRANT EXECUTEs ON func behave as one would expect..".

What do you think?
