### ISSUE TITLE
Show standard way to deploy on EC2/Ubuntu/Nginx

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest-docs#3]
Original issue: https://github.com/begriffs/postgrest/issues/531

**Comment by steve-chavez** [comment]
Man, this is so easily done with NixOps nowadays. Having a single config file with no containers involved. It's even possible to specify pg extensions.

But I guess people have managed with docker compose for a long time now.

I think it'd be better to not focus on the ops part seeing we're missing so much core stuff.
