### ISSUE TITLE
Move the CHANGELOG to docs

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#340]
Right now we duplicate the CHANGELOG from https://github.com/PostgREST/postgrest/blob/master/CHANGELOG.md to the docs. That's not ideal and gets cumbersome.

Instead we can have the CHANGELOG on the docs and have a link on the github release page.

I've seen godot does it like this: https://github.com/godotengine/godot/releases.

I believe this would be better since sometimes we need to link the CHANGELOG entry to the newly added doc section.

We can announce this change on the upcoming release.

(Got this from the discussion on https://github.com/monacoremo/postgrest-sessions-example/issues/19#issuecomment-639770101)

**Comment by steve-chavez** [comment]
Another idea would be to use a convention on the git commits, and create a changelog based on that. Like https://github.com/semantic-release/semantic-release#commit-message-format.

**Comment by wolfgangwalther** [comment]
Yes, please. But how are we going to handle references to docs sections with that?

**Comment by wolfgangwalther** [comment]
Also looking at #367, where a lot of the new config options are missing: Have you considered moving the docs into the main repo?

This would allow us to:
- Make sure that every PR is merged with the corresponding docs
- Have the changelog in one repo only and also track those immediately with the PR
- Maybe even have a CI check to notify us if a Changelog entry is missing

This would make it a lot easier to track docs updates and make sure the latest docs are always up2date. This is even more important now, that we have nightly builds.

**Comment by steve-chavez** [comment]
> Have you considered moving the docs into the main repo?

@wolfgangwalther It used to be that way, but it was split a long time ago.

The main problem is that the docs don't only contain PostgREST features. It also contains tutorials, how-tos, explanations, blog posts, links, landing page, etc. Having all the previous changes on a single repo would:

- Trigger a CI rebuild on a each change. e.g. a simple "typo fix" will do that. And we have several CIs(maybe one more later). It looks hard to control.
- Makes history on the main repo harder to track.

Btw, Remo also asked me this before: https://github.com/monacoremo/postgrest-sessions-example/issues/19#issuecomment-634897040.

**Comment by steve-chavez** [comment]
Just noted that Godot keeps more than one CHANGELOG:

- Code changelog: https://github.com/godotengine/godot/blob/3.3/CHANGELOG.md
- Docs changelog: https://godotengine.org/article/release-candidate-godot-3-3-3-rc-1
- These seem autogenerated:
  - CHANGELOG by author: https://downloads.tuxfamily.org/godotengine/3.3.3/rc1/Godot_v3.3.3-rc1_changelog_authors.txt
  - Cronological CHANGELOG: https://downloads.tuxfamily.org/godotengine/3.3.3/rc1/Godot_v3.3.3-rc1_changelog_chrono.txt

One thing with our [docs changelog](https://postgrest.org/en/v8.0/releases/v8.0.0.html) is that it seems pretty much a copy of the code changelog(plus references). It needs a section like "Highlights".

**Comment by steve-chavez** [comment]
I'll close this since now we do a more readable version of the changelog in the docs: https://postgrest.org/en/v9.0/releases/v9.0.0.html

It takes a bit more work, but I think it's worth it - we can highlight/classify features(Horizontal Filtering, Administration, etc) and we get linkable sections.
