### ISSUE TITLE
Caller's IP Address available via a GUC?

### ISSUE THREAD

**Issue by bradleyf** [PostgREST/postgrest-docs#358]
Hmmm.  I thought it was possible to retrieve the IP address of the Postgrest request being processed via a postgresql GUC.    Like the claims and http headers.  Seems it isn't.

Any thoughts as to how to obtain this from the postgresql side?

**Comment by steve-chavez** [comment]
@bradleyf Are you proxying with nginx?

If so, you could extend the config [here](http://postgrest.org/en/v7.0.0/admin.html#hardening-postgrest) with:

```
proxy_set_header   X-Real-IP          $remote_addr;
```
Then you could get the ip on pg side with: `current_setting('request.header.x-real-ip', true)`

**Comment by bradleyf** [comment]
Yes, I am.   I’ll give it a try.    Thanks!

**Comment by bradleyf** [comment]
That worked!
