### ISSUE TITLE
"No function matches the given name" on valid condiction for the RPC returning table

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest-docs#359]
Suppose that these URLs are working fine:

*  rows can be filtered, http://localhost:3000/t/?x=eq.1
*  columns can be filtered, http://localhost:3000/t/?select=x
* we can call a RPC, http://localhost:3000/rpc/f_ret_t?p_x=2

Now suppose that *f_ret_t*  is a function returning a table like *t*... RPC columns can be filtered,<br/> http://localhost:3000/rpc/f_ret_t?p_x=2&select=x
And is expected that *t* rows can be filtered by `x=eq.1`, so I try <br/> http://localhost:3000/rpc/f_ret_t/?p_x=2&x=eq.1  <br/>but it results in ERROR, *"No function matches the given name ..."*. I am using non-conflicting names, "paramter x" is not *x* but *p_x*. Even with that care, is impossible to filter a function.

PS1: of couse, the function overloading hypotesis is the problem here, but we can avoid it, as in the illustration.

PS2: there are a second and general problem with PostgREST that is the filter by a name that is not in the SELECT clause. For example  http://localhost:3000/t/?select=a,b&x=eq.1

**Comment by steve-chavez** [comment]
> http://localhost:3000/rpc/f_ret_t/?p_x=2&x=eq.1

Only `p_x` should be taken as an argument here, every query param value that starts with `eq./lt./etc` will be considered as a filter and not as an argument.

I'm pretty sure that call should work. Maybe share a reproducible test case so others can confirm.

**Comment by wolfgangwalther** [comment]
And when you're able to provide a reproducible test-case, feel free to open an Issue at the PostgREST main repo, because this would be a bug and not about the docs.
