### ISSUE TITLE
Calling a function that has a json/jsonb parameter?

### ISSUE THREAD

**Issue by bradleyf** [PostgREST/postgrest-docs#360]
Is this possible?     I can't get it to work?

**Comment by steve-chavez** [comment]
Hmm.. it should work. What have you tried?

Check this section: http://postgrest.org/en/v7.0.0/api.html#calling-functions-with-a-single-json-parameter

**Comment by wolfgangwalther** [comment]
@bradleyf where you able to get it to work? Is there any way we should improve the documentation on this feature?
