### ISSUE TITLE
Add notice about current_setting behavior

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#362]
Under http://postgrest.org/en/v7.0.0/api.html#http-logic.

Related to https://github.com/PostgREST/postgrest/issues/1642.

Recommend to add a wrapper function as in https://github.com/PostgREST/postgrest/issues/1642#issuecomment-720566013.

**Comment by profiluefter** [comment]
Hi, I just ran into this issue and it took me some while to find the mentioned issue. Could we add this to the docs please?

**Comment by steve-chavez** [comment]
@profiluefter What would you suggest? A warning on https://postgrest.org/en/stable/references/transactions.html#transaction-scoped-settings ?

**Comment by profiluefter** [comment]
> @profiluefter What would you suggest? A warning on https://postgrest.org/en/stable/references/transactions.html#transaction-scoped-settings ?

Yes, exactly. A link to the issue and/or a codesnippet using `nullif` would also be nice i think
