### ISSUE TITLE
PGRST_SERVER_PROXY_URI in docker-compose instructions is incorrect

### ISSUE THREAD

**Issue by jat255** [PostgREST/postgrest-docs#379]
I'm very new to PostgREST, so this might be wrong, but I think the instructions for the docker-compose install at https://postgrest.org/en/v7.0.0/install.html#docker are incorrect. In that compose file example, it specifies `PGRST_SERVER_PROXY_URI` should be http://127.0.0.1:3000. Regardless of what I put in this field, my openAPI response always showed the host as "0.0.0.0". After some poking around the code, it looks like this environment variable should actually be `PGRST_OPENAPI_SERVER_PROXY_URI` instead.

If someone can confirm this, I'm happy to make a PR to fix it in the docs, but I want to make sure this is the correct thing to do, first.

**Comment by wolfgangwalther** [comment]
Yes, that's correct, this has been changed. PR welcome!

**Comment by jat255** [comment]
Ok, submitted!
