### ISSUE TITLE
tutorial 0 + tutorial 1 password and jwt issue

### ISSUE THREAD

**Issue by vks2** [PostgREST/postgrest-docs#381]
Am I right with this: if i implement your example in tutorial 0 and 1 I would have an REST API service open for anyone, because of 
create role web_anon **nologin**;
If I proceed with Tutorial 1 and do it step-by-step I still do not require any password when call it from localhost:3000 
could you please share all tutorial.conf used in Tutorial 1, not only this: jwt-secret = "<the password you made>"
because it's an REST api open for anyone if you have your IPv and port 3000 open to public.
Am I wrong with smth?
Thanks much.

**Comment by vks2** [comment]
Thank you for your quick and very detailed answer. If in tutorial 1 I do not pass any password in my request to localhost, Postgrest will redirect it to web_anon role and I'll still have the problem of an API open to everyone. An I right with this? So I just need to set a password in Postgresql to all users that we create in Tutorials, including web_anon and todo_user if I do not want to make a reverse proxy in front of Postgresql. 

> but I am sure you will not expose your database port to the public

You mean 3000 or 5433 in my example?
Thank you in advance.

**Comment by wolfgangwalther** [comment]
> Thank you for your quick and very detailed answer. If in tutorial 1 I do not pass any password in my request to localhost, Postgrest will redirect it to web_anon role and I'll still have the problem of an API open to everyone. An I right with this?

It depends on what "API open to everyone" means to you. There's two ways of looking at that:

1. can everyone connect to `http://your-ip:3000`, so the port is open to the public?

2. or: can everyone access data through requests with the anonymous role?

Of course 2 is only possible when 1 is possible as well. When you are concerned about 2, you need to remove all privileges from the web_anon user. When you are concerned about 1, you need to add a reverse proxy.

> So I just need to set a password in Postgresql to all users that we create in Tutorials, including web_anon and todo_user if I do not want to make a reverse proxy in front of Postgresql.

Setting a password in PostgreSQL will not do anything. The PostgreQL passwords are not used at all. In tutorial 0, you set this in your postgrest config file:

```
db-anon-role = "web_anon"
```

This tells PostgREST to switch to the web_anon user for anonymous requests. Take away the privileges of this user to limit anonymous access. In tutorial 0 you granted the following privileges to the anonymous role:

```sql
grant usage on schema api to web_anon;
grant select on api.todos to web_anon;
```
You can reverse that with

```sql
revoke usage on schema api from web_anon;
revoke select on api.todos from web_anon;
```

Now, you will not be able to access the todos list with your anonymous user.



> You mean 3000 or 5433 in my example?

3000 is PostgREST - you need this open, if you're not using a reverse proxy.

5433 (5432) is the database port. This should be **closed** to the public.

**Comment by vks2** [comment]
Dear Wolfgang , thank you for detailed answer.

Just to close my issue, should I only deal with pre-request procedures in postgrest and postgres if I do not want any anonymous authentication at all? Is there any other way to allow access to schema 'api' only to users with passwords (jwt , for example) and block anonymous calls?

Thanks much and have a great weekend!

PS did you think about renaming your valuable product? Google always changes for postgres my postgrest query.

**Comment by wolfgangwalther** [comment]
> Just to close my issue, should I only deal with pre-request procedures in postgrest and postgres if I do not want any anonymous authentication at all?

There are many more use-cases for `pre-request` functions. But yes, you could probably block anonymous requests there as well.

> Is there any other way to allow access to schema 'api' only to users with passwords (jwt , for example) and block anonymous calls?

```sql
revoke usage on schema api from web_anon;
```

will do exactly that. What other way do you need / why does this not work for you?

**Comment by vks2** [comment]
Thank you. It works indeed. Now struggling with base64 pass error, should save it in a separate file.
Thank a lot!

**Comment by wolfgangwalther** [comment]
Yes, I think that would be good. I briefly thought about recommending to set `db-anon-role` to an invalid role, but I wasn't sure about the consequences for our schema cache queries.

What if we just make `db-anon-role` optional? No anon role -> no anon access!

**Comment by wolfgangwalther** [comment]
> What if we just make `db-anon-role` optional? No anon role -> no anon access!

+ the more optional settings we have, the more of those can be read from in-database configurations.

**Comment by steve-chavez** [comment]
> What if we just make db-anon-role optional? No anon role -> no anon access!

I like it! That would be the simplest way.
