### ISSUE TITLE
Remove empty object fields from output (json_strip_nulls)

### ISSUE THREAD

**Issue by Sjoerd82** [PostgREST/postgrest-docs#392]
To improve performance (bandwidth, download time) it would be **very** helpful if there were an option to remove empty fields from the output, similar to the Postgresql `json_strip_nulls()` function.

Perhaps by adding a parameter we could get:

```
GET /people
Prefer: stripnull=true
[
  { "name": "J Doe", "age": 62, "height": 70 },
  { "name": "Janus", "age": 10, "height": 55, "country":"Somewhere" }
]
```

Instead of:
```
GET /people
[
  { "name": "J Doe", "age": 62, "height": 70, "country":null },
  { "name": "Janus", "age": 10, "height": 55, "country":"Somewhere" }
]
```

In Postgres this is already possible:

```
SELECT json_strip_nulls(
	   json_build_object(
		  'name', name
		 ,'age', age
		 ,'height', height
		 ,'country',country
	 )) json_output
  FROM people
```

Long, wide, but sparsely populated tables, especially with long attribute names seize up a large percentage of the download.
A stripnull (or whatever you should call it) would be a blessing.

**Comment by steve-chavez** [comment]
@Sjoerd82 Yeah, this is definitely a good idea.

Now that I remember, we're already tracking it in https://github.com/PostgREST/postgrest/issues/1601.

Let's continue there?

**Comment by Sjoerd82** [comment]
Ah, good to see that I'm not the only one. Closing, because this is a duplicate of 1601.
