### ISSUE TITLE
Add text OPENAPI to line 181

### ISSUE THREAD

**Issue by bpjetursson** [PostgREST/postgrest-docs#410]
Please check
https://github.com/PostgREST/postgrest-docs/blob/9ff0da96970f8e446e733d2573b6ebbea60e18e8/install.rst#L181

I believe, it should be `PGRST_OPENAPI_SERVER_PROXY_URI `instead.

**Comment by laurenceisla** [comment]
Yes, this was corrected on the docs for the latest release. See: https://postgrest.org/en/latest/install.html#containerized-postgrest-and-db-with-docker-compose
