### ISSUE TITLE
Add multiple methods of fetching data from the API

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest-docs#411]
Currently, all of the API request examples are using CURL. More examples using Javascript libraries like `axios` or the `fetch` API would help the users implementing web apps with PostgREST (e.g. this [gitter comment](https://gitter.im/begriffs/postgrest?at=60e6389c457e19611a3e139f))

We could use [code tabs](https://sphinx-code-tabs.readthedocs.io/en/latest/#usage) with a CURL default to organize the methods.

**Comment by steve-chavez** [comment]
Great idea!

> Currently, all of the API request examples are using CURL

Actually the examples are not even using CURL, just an HTTP snippet that's not easily translatable to CURL in many cases. For example, the POST/PATCH requests require extra arguments from curl.

**Comment by steve-chavez** [comment]
Just the current HTTP snippets plus CURL calls would be a good start.

Another advantage of having curl calls is that our references would be testable(ref https://github.com/PostgREST/postgrest-docs/issues/371).

**Comment by steve-chavez** [comment]
Closing this since we already have curl snippets https://postgrest.org/en/stable/references/api/tables_views.html.

axios or other libs are looking like much work for now.
