### ISSUE TITLE
Document special values regarding timestamptz filters

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#426]
Adding the timezone to the value works as discovered on [gitter](https://gitter.im/begriffs/postgrest?at=6116ac618fc359158c6b8e85).

```http
GET /articleStars?createdAt=lt.2020-01-01+00:00:00+Australia/Sydney
```

Using special values such as "now" or "yesterday" also work([ref1](https://github.com/PostgREST/postgrest/issues/1597#issuecomment-701529949), [ref2](https://github.com/PostgREST/postgrest/discussions/1650#discussioncomment-248566)).

**Comment by steve-chavez** [comment]
I think this + PostGIS/hstore(https://github.com/PostgREST/postgrest-docs/issues/273) would fit good on a "Working with types" page.

**Comment by laurenceisla** [comment]
We could also add a case with custom types with a string array field, for instance:

```sql
create type strarr as (a text[]);

create function api.fn_strarr(m strarr) returns strarr as $$
  SELECT m;
$$ LANGUAGE SQL;

select * from api.fn_strarr( '("{a,b,c}")');
```

```bash
curl http://localhost:3000/rpc/fn_strarr \
  -X POST -H "Content-Type: application/json" \
  -d '{ "m": "(\"{a,b,c}\")" }'
```

From this comment https://gitter.im/begriffs/postgrest?at=61a4cee6abdd6644e3aef823
