### ISSUE TITLE
https://postgrest.org redirects to v7.0.0 of the docs

### ISSUE THREAD

**Issue by robertsosinski** [PostgREST/postgrest-docs#427]
Notice when I go to https://postgrest.org I get redirected to https://postgrest.org/en/v7.0.0/. When I look at the headers, it shows the following:

```
$ curl -i https://postgrest.org
HTTP/2 302
date: Sun, 15 Aug 2021 23:13:29 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://postgrest.org/en/v7.0.0/
```

Now that v8.0.0 is out, should this be the "default" redirect?

Thanks!

**Comment by wolfgangwalther** [comment]
Not sure whether Steve already changed it in the mean-time, but I just checked and I am getting redirected to v8.0. The setting at readthedocs seems to be set correctly, too.

So either it's working as expected or was already fixed.

Does it work for you, too, now?

**Comment by steve-chavez** [comment]
@robertsosinski Thanks for the heads up!

@wolfgangwalther Yes, just a while ago I've changed the default to redirect to v8.0. Should be fixed :+1:
