### ISSUE TITLE
Error in Windows BUT WORKING FINE IN MACOS when query Postgrest server 

### ISSUE THREAD

**Issue by cgxinyi** [PostgREST/postgrest-docs#438]
Error in Windows BUT WORKING FINE IN MACOS:
Error in Postman to Postgrest Server:
Error1:
{
    "hint": null,
    "details": "Custom parameter names must be two or more simple identifiers separated by dots.",
    "code": "42602",
    "message": "invalid configuration parameter name \"request.header.content-type\""
}
Error2:
{
    "hint": null,
    "details": "Custom parameter names must be two or more simple identifiers separated by dots.",
    "code": "42602",
    "message": "invalid configuration parameter name \"request.header.user-agent\""
}

Error in Docker Postgres:
postgres         | 2021-10-02 05:03:39.276 UTC [40] ERROR:  invalid configuration parameter name "request.header.user-agent"
postgres         | 2021-10-02 05:03:39.276 UTC [40] DETAIL:  Custom parameter names must be two or more simple identifiers separated by dots.
postgres         | 2021-10-02 05:03:39.276 UTC [40] STATEMENT:  select set_config($1, $2, true), set_config($3, $4, true), set_config($5, $6, true), set_config($7, $8, true), set_config($9, $10, true), set_config($11, $12, true), set_config($13, $14, true), set_config($15, $16, true)

How to reproduce:
curl --location --request GET 'localhost:3000/<TABLE_NAME>'

Docker compose:

`version: '3.1'

services:
  postgres:
    image: "postgres" # use latest official postgres version
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ../doc/dbschema.sql:/docker-entrypoint-initdb.d/1-schema.sql

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    env_file:
       - database.env # configure postgrest
    depends_on:
      - postgres

volumes:
  pg_data:
  es_data:
    driver: local
`

**Comment by steve-chavez** [comment]
@cgxinyi This must be cause your docker compose postgres version is unpinned and it's pointing to postgres 14(latest) - which is incompatible with PostgREST right now, see https://github.com/PostgREST/postgrest/issues/1857. We have a fix in progress in https://github.com/PostgREST/postgrest/issues/1857.
