### ISSUE TITLE
in-database configuration not working

### ISSUE THREAD

**Issue by bhvngt** [PostgREST/postgrest-docs#487]
I am using a [supabase](https://supabase.com) [docker compose](https://github.com/supabase/supabase/blob/93d0dbf2c55596ef388cc2452da74b7a67ca811b/docker/docker-compose.yml#L75) container for the purpose of development. I have an app specific schema where I wanted to try out [in-database configuration](https://postgrest.org/en/stable/configuration.html#in-database-configuration).

Default available schema in the docker-compose files are `public,storage`;

I have executed following commands to change this settings using in-database configuration
```sql
ALTER ROLE authenticator SET pgrst.db_schema = "public,schema1,storage";
NOTIFY pgrst, 'reload config';
```
Now when I issue following curl command
```bash
curl -H "apikey: <SUPABASE_ANON_KEY>" -H "Accept-Profile: schema1" http://localhost:3000/rest/v1/test
```
I get following response
```json
{"message":"The schema must be one of the following: public, storage"}
```

I do see following log message on the docker logs of pgrest service `Config re-loaded`. Even then it does not look like the in-database configuration changes are perculated.

Is there a way to query the current set of postgrest configuations. When I query 
```sql 
SELECT  pd.datname, pa.rolname, pr.*
FROM pg_catalog.pg_db_role_setting pr
    JOIN pg_database pd ON pr.setdatabase = pd.oid
    JOIN pg_authid pa ON pr.setrole = pa.oid
```

I get following result
|datname |rolname      |setdatabase|setrole|setconfig                                 |
|--------|-------------|-----------|-------|------------------------------------------|
|postgres|authenticator|13757      |16446  |{pgrst.db_schema=public,innerview,storage}|

### Questions
- Am I missing any step to change and reload in-database config?
- Is this the right way to query current settings?
- Is there  a way to query all of the configurations?

**Comment by wolfgangwalther** [comment]
Hm. I just tried those exact steps with a bare postgrest instance myself and it worked for me.

Can you try to run postgrest with `--dump-config`? This will give you the exact configuration it's running with.

I also note, that the result of the query and the `ALTER ROLE` command you showed above, don't match:
- `ALTER ROLE` does not have `IN DATABASE` - but the result has a `setdatabase` oid listed
- The values don't match: `public,schema1,storage` vs `public,innerview,storage`

You can change your query to have a `LEFT JOIN pg_database` - this should show you the database-independent (those without `IN DATABASE` as above), too.

**Comment by wolfgangwalther** [comment]
Oh. I I think I just found the problem.

In the database you need to use `db-schemas` (plural) instead of `db-schema`.

`db-schema` is the old setting, `db-schemas` is the new setting. We have kept the old alias for backwards compatibility - but it seems this only works for environment variables and the config file. The in-database configuration does not support the backwards compatible alias.

This makes sense, because the name change and the ability to set in-database configuration were released together - so there was no need to keep backwards compatibility in that case.

The only problem here is: We have not documented the new names, yet. The docs only refer to the old name - and the example for in-database configuration is just plain wrong.

**Comment by wolfgangwalther** [comment]
The example in the docs is now fixed.

**Comment by bhvngt** [comment]
Thanks @wolfgangwalther. After couple of trials and error, I figured the root cause of my issue. `DB-URI` was set to different user while I was altering `authenticator` role to change the settings. Matching both of them and using `db-schemas` (plural), I was able to fix my issue. Thanks a ton for your help.

> I also note, that the result of the query and the `ALTER ROLE` command you showed above, don't match:
> 
> * `ALTER ROLE` does not have `IN DATABASE` - but the result has a `setdatabase` oid listed
> * The values don't match: `public,schema1,storage` vs `public,innerview,storage`
> 

Sorry, these were typos. I had incorrectly framed my issue.
