### ISSUE TITLE
Incorrect link in Community Tutorials -> Client-Side-Libraries section

### ISSUE THREAD

**Issue by FooBar1969** [PostgREST/postgrest-docs#522]
In the list of client side libraries in the community tutorials the link for the swift library sends you to the kotlin library at supabase: 

https://github.com/supabase-community/postgrest-kt

I think that it was meant to go here: 

https://github.com/supabase-community/postgrest-swift

**Comment by steve-chavez** [comment]
True. @FooBar1969 Could you help us with a PR?

**Comment by FooBar1969** [comment]
Yes. (let me read up on the contributing guidelines... ;) )

**Comment by steve-chavez** [comment]
Thanks for the contrib!
