### ISSUE TITLE
Are tree relations supported? A table with an fk to itself

### ISSUE THREAD

**Issue by yevon** [PostgREST/postgrest-docs#525]
I'm trying to build a url within a table that has a relation to itself by a FK (Typicall in tree relations). Is this case supported? Message I'm hitting is:

{
  "hint": "If a new foreign key between these entities was created in the database, try reloading the schema cache.",
  "message": "Could not find a relationship between menu_entries and menu_entries in the schema cache"
}

Or should I build a view in this case?

**Comment by steve-chavez** [comment]
Yes, self-references are supported but have limitations. See https://github.com/PostgREST/postgrest/issues/1643#issuecomment-721417728.

**Comment by yevon** [comment]
Perfect thanks! I got it!
