### ISSUE TITLE
support for swagger configuration options, especially security scheme and security/authorization

### ISSUE THREAD

**Issue by tvogt** [PostgREST/postgrest-docs#555]
_This feature request especially applies to the docker image that is tightly integrated with swaggerapi/swagger-ui_

Since PostgREST auto-generates the OpenAPI specs, it needs a way to add options such as security scheme or security/authorization (which makes permissions visible with a lock icon - see https://swagger.io/docs/specification/authentication/).

This could be accomplished in the COMMENT which is already a supported feature. This way it would be stored in the database and survive dump/import.

**Comment by steve-chavez** [comment]
This is the same feature request as https://github.com/PostgREST/postgrest/issues/1082#issuecomment-1178662247 right?

Let's follow up there. Laurence is checking the implementation now.
