### ISSUE TITLE
CREATE EXTENSION IF NOT EXISTS "ltree"

### ISSUE THREAD

**Issue by Siniinik** [PostgREST/postgrest-docs#566]
Will query support complement ltree and lquery queries

{
  "hint": null,
  "details": null,
  "code": "42704",
  "message": "type \"ltree\" does not exist"
}

**Comment by steve-chavez** [comment]
We have support for some `ltree` operations: https://github.com/PostgREST/postgrest/issues/2064

Can you share the curl snippet of the request you're making?

**Comment by Siniinik** [comment]
I made a request through a stored procedure

CREATE  OR REPLACE FUNCTION uop2.removenode(id text )  RETURNS void
AS $$ BEGIN
    PERFORM obj.idobjectworld::text  FROM uop2.objectworld as obj WHERE obj.path::ltree ~ '*{1}' ;
END $$ LANGUAGE plpgsql;

###
POST http://uop01:850894Bo@1ppmop01.dev.aorti.tech:88/mpmop/api/rpc/removenode
Content-Type: application/json
Content-Profile: uop2

{
  "id": 29
}

The answer always came one
Content-Type: application/json; charset=utf-8

{
  "hint": null,
  "details": null,
  "code": "42704",
  "message": "type \"ltree\" does not exist"
}

**Comment by laurenceisla** [comment]
Maybe the `public` schema needs to be added in the [`db-extra-search-path`](https://postgrest.org/en/v10.0/configuration.html#db-extra-search-path) configuration. If `ltree` was installed in another schema, you may need to add that one to the configuration instead (or specify it in the function e.g. `obj.path::other_schema.ltree`) . You can see the schema with this query:

```sql
select typnamespace::regnamespace from pg_type where typname like 'ltree';
```

**Comment by Siniinik** [comment]
Thanks everything worked
