### ISSUE TITLE
Donation for the project

### ISSUE THREAD

**Issue by Siniinik** [PostgREST/postgrest-docs#567]
Unfortunately PayPal does not work in all countries. You helped me a lot today. And I really want to thank you and transfer the amount of money. 
Do you have the opportunity to connect a donat that works in our country. With donationalerts.com

This is not an advertisement. Link to the solved problem https://github.com/PostgREST/postgrest-docs/issues/566

**Comment by laurenceisla** [comment]
The only alternative there is right now is to become a Patreon at https://www.patreon.com/postgrest. Don't worry if you can't though, thank you for the offer.

**Comment by Siniinik** [comment]
Thank you again
