### ISSUE TITLE
Add Ubuntu quickstart example to Ecosystem

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest-docs#572]
Nice quickstart with dependencies installation and pgjwt usage in https://github.com/simplygeo/postgrest-tools

From: https://gitter.im/begriffs/postgrest?at=632c759d7ccf6b6d45e99b88

**Comment by steve-chavez** [comment]
Seems there's not much activity on that repo. For example, pg 15 is not added yet. I'll keep an eye on it but for now we can close.
