### ISSUE TITLE
Document how to use Heroku + RDS

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest-docs#58]
* Using the deploy to heroku button on the repo
* Describe available options
* Show the anatomy of a postgresql connection string
* Mention RDS IP permissions
* Keeping the DB geographically near the heroku dyno (virginia region)

**Comment by steve-chavez** [comment]
I'll close citing the same reason as in https://github.com/PostgREST/postgrest-docs/issues/3#issuecomment-521739306.

Priority should be core functionality and ppl have been managing.
