### ISSUE TITLE
Change "Anonymous access is disabled" broke SQL User Management section?

### ISSUE THREAD

**Issue by fjf2002** [PostgREST/postgrest-docs#580]
I think the breaking change "Anonymous access is disabled by default" in v10 broke the docs at https://postgrest.org/en/stable/auth.html#sql-user-management .

The guide advises to try `POST /rpc/login HTTP/1.1` before the permissions-section, where the role anon is yet to be created:

```create role anon noinherit;```

(I noticed while writing the howto mentioned in #562)

**Comment by steve-chavez** [comment]
True. We'd need to add that `db-anon-role = "anon"` is required

**Comment by fjf2002** [comment]
Also the sentence

> If auth succeeds, it switches into the user role specified by the request, otherwise it switches into the anonymous role.

... probably needs an addition, something like:

> ... but only if [db-anon-role](https://postgrest.org/en/stable/configuration.html#db-anon-role) is set; otherwise it will kinda fail?
