### ISSUE TITLE
headers tx-settings are lowercase

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#627]
We need to document this.

> It is also worth noting that, due to the aforementioned change, request headers are effectively case-sensitive now, whereas before they were essentially case-insensitive. What I mean is, before you could do

```sql
SELECT current_setting('request.header.X-My-Header');
```

and you would get the value you're looking for, whereas now, if you do

```sql
SELECT current_setting('request.headers')::json->>'X-My-Header';
```

it will _not_ work (and it will be confusing to debug!). You can now only access the headers by their lower-cased version:

```sql
SELECT current_setting('request.headers')::json->>'x-my-header';
```

_Originally posted by @elimisteve in https://github.com/PostgREST/postgrest/issues/1857#issuecomment-1555443344_

**Comment by steve-chavez** [comment]
Looks like the lowercasing is a remnant of when we used the header name as part of the GUC name: 
https://github.com/PostgREST/postgrest/blob/aa53623aac0e13dbeedb6e8414d7c52b0ad936d9/src/PostgREST/ApiRequest.hs#L172

For the new JSON GUCs, we don't need to lower case the header names.

Unfortunately we cannot fix this because at this point it would be a major breaking change.

Will just document the gotcha instead.

cc @laurenceisla

**Comment by elimisteve** [comment]
> Will just document the gotcha instead.

Sounds good 👍.
