### ISSUE TITLE
Move release notes pages to github releases

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#644]
Just saw [QuestDB release page](https://github.com/questdb/questdb/releases/tag/7.2). Really cool, made me remember we have full markdown support there.

How about if we deprecate the docs release notes and move them to GH release page? https://postgrest.org/en/stable/releases/v11.1.0.html

### Advantages

- DRY. We no longer have to duplicate the CHANGELOG entries. Features can be linked to docs sections.
- Users get notifications on releases

### Notes

Seeing the QuestDB page, I realize it's better to have frequent releases. That way the release post overview can be focused.

**Comment by steve-chavez** [comment]
@laurenceisla @wolfgangwalther WDYT?

**Comment by laurenceisla** [comment]
I like the idea, there could be a single Release page in the docs that redirects to each of the GH releases. A thing to keep in mind is that we must add links to the docs for the relevant features, changes, etc. so we should keep the docs up to date for that reason (even if the release page can be updated later).

**Comment by steve-chavez** [comment]
I believe the end result looks better: https://github.com/PostgREST/postgrest/releases/tag/v11.2.0

That being said, it was a bit of pain having to sync the docs with core. Doing https://github.com/PostgREST/postgrest/issues/2814 should make this easier.
