### ISSUE TITLE
The table of configuration parameters is not responsive

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest-docs#662]
On vertical screens, the table does not show the env/database configuration names:

![test](https://github.com/PostgREST/postgrest-docs/assets/18169764/d5e7c6a9-f94a-4300-b08f-255fc3ced6b5)

We could:
- Add a horizontal scroll to the table
- Rollback to env/database names below each configuration, e.g.: https://postgrest.org/en/v11.0/references/configuration.html#admin-server-port

**Comment by steve-chavez** [comment]
@laurenceisla Good catch!

So when I put it all in the table my motivation was to DRY the configs. 

> Rollback to env/database names below each configuration, e.g.:

I believe that's the solution. So for example on https://postgrest.org/en/v11.1/references/connection_pool.html#dynamic-connection-pool, I have to inline the default value of the config. If each default is on the config section that wouldn't be needed.

So to DRY things we need to remove the table and go back to the previous layout.
