### ISSUE TITLE
Drop all plain HTTP snippets in favor of `curl` commands

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest-docs#720]
## Problem

It's easy to forget adding both `curl` and `HTTP` syntax snippets. See: https://github.com/PostgREST/postgrest-docs/pull/719

## Solution

Drop all existing HTTP snippets. Focus on only making the `curl` snippets readable from now on.

**Comment by laurenceisla** [comment]
Yes, I agree. I guess `curl` snippets are more useful for practical purposes than the HTTP ones. Also a consistent format should be kept for the snippets (could help if we want to add other snippets in the future).
