### ISSUE TITLE
Missing entries in Preferences section

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest-docs#729]
[Some preferences](https://postgrest.org/en/latest/references/api/preferences.html?highlight=max-affected#prefer-header) are missing in the list:

- `Prefer: params`
- `Prefer: tx`
- `Prefer: max-affected`

**Comment by steve-chavez** [comment]
Taimoor might pick up the `max-affected` since it's a recent addition.

The other two are definitely missing. It should be mentioned that `params` is deprecated in favor of a single unnamed param on a proc.
