### ISSUE TITLE
Avoid Globbing in Curl examples

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest-docs#744]
Noticed in [an SO answer](https://stackoverflow.com/a/77821831/17265105) that curl does Globbing by default when `{}` is present. So these should be percent encoded in the examples or use the `-g` parameter (I prefer the latter, looks cleaner).

**Comment by steve-chavez** [comment]
@laurenceisla IIRC using single quotes `'` also prevents the globbing.

**Comment by laurenceisla** [comment]
@steve-chavez Just tested it, it still does the globbing with single quotes.
